#ifndef WIFIPARAMS_H_
#define WIFIPARAMS_H_

#define MAX_WIFI_PASS_LENGTH 64
#define MAX_WIFI_SSID_LENGTH 32
#define MAC_STRING_LENGTH 14 

#define STORED_CONNECTION_STATE_ADDRESS 0x00
#define WIFI_SSID_ADDRESS 0x01
#define WIFI_PASS_ADDRESS 0x21
#define WIFI_ENCRYPTION_ADDRESS 0x61

#define WIFI_LAN_CONNECTON 'L'
#define WIFI_DIRECT_CONNECTION 'D'
#define NO_STORED_CONNECTION 'C'
#define START_OF_SSID_PTR 6
enum ENCRYPTION_TYPE { WPA = '1', WPA2, WEP, OPEN };



#endif /* WIFIPARAMS_H_ */